In [1]:
import numpy as np

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

Матрицы А и В не квадратные, одинаковой размерности. Соответственно умножать их можно, если 1 из них транспонировать. Если транспонировать B, получится матрица 4*4 Если транспонировать A, то получится матрица 2*2

In [2]:
A = np.random.randn(4, 2)
B = np.random.randn(4, 2)
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Результат умножения А * В.Т:')
print(A.dot(B.T))
print('Результат умножения А.Т * В:')
print(B.T.dot(A))

Матрица А:
[[ 0.67411149  0.12238058]
 [-0.22846962 -0.52204299]
 [-1.15726267  0.90986295]
 [-0.4620428  -1.07058231]]
Матрица В:
[[-0.38252268  0.67282025]
 [ 0.38642145 -0.49023062]
 [-0.706405   -1.05983892]
 [-0.39132923  1.89741862]]
Результат умножения А * В.Т:
[[-0.1755228   0.20049643 -0.60589943 -0.03159233]
 [-0.26384629  0.1676359   0.71467356 -0.90112726]
 [ 1.05485343 -0.8932338  -0.14681204  2.17926161]
 [-0.54356761  0.34628899  1.46103414 -1.85053196]]
Результат умножения А.Т * В:
[[ 0.65215849 -0.47232354]
 [ 0.91538207 -2.65738938]]


б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;
Матрицы 𝐴*𝐵 имеет размерность 2 3 
Матрица В*А не существует. 
Можно сделать матрицу A.T * B.T. Полученная матрица будет иметь размерность 3 * 2

In [3]:
A = np.random.randn(2, 5)
B = np.random.randn(5, 3)
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Результат умножения А * В:')
print(A.dot(B))
print('Результат умножения В.Т * А.Т:')
print(B.T.dot(A.T))

Матрица А:
[[-1.40790427  0.03499508  0.47097543  1.08006868 -0.68152984]
 [-0.63849317  0.58321519 -0.18179789  0.96997396  0.19459141]]
Матрица В:
[[ 1.59707269e+00 -1.07203170e+00  1.75863614e-01]
 [ 2.23699769e-01  4.92680780e-04  5.77118729e-01]
 [-1.74984557e+00  1.12454059e+00  4.67320593e-01]
 [-1.48962555e+00 -1.36664884e+00 -3.19183432e-01]
 [ 1.21405675e+00  1.28303415e+00 -3.12573152e+00]]
Результат умножения А * В:
[[-5.50114515 -0.31153443  1.77823298]
 [-1.77978964 -0.59561322 -0.77850132]]
Результат умножения В.Т * А.Т:
[[-5.50114515 -1.77978964]
 [-0.31153443 -0.59561322]
 [ 1.77823298 -0.77850132]]


в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;
Обе матрицы 𝐴𝐵 и 𝐵𝐴 определены 
Матрицы 𝐴*𝐵 имеет размерность 8 * 8. 
Матрица В * А имеет размерность 3 * 3

In [4]:
A = np.random.randn(8, 3)
B = np.random.randn(3, 8)
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Результат умножения А * В:')
print(A.dot(B))
print('Результат умножения В * А:')
print(B.dot(A))

Матрица А:
[[-0.3038558   0.47284615  1.67539979]
 [ 0.07820611 -0.95591296 -0.51068469]
 [ 0.9538496  -1.64016137 -0.9274731 ]
 [ 0.62177297  0.87974155  3.15799277]
 [-0.78978335  1.55938763  0.32361112]
 [ 1.69106364 -1.40273766 -1.28905455]
 [-0.9712102   1.01444792  1.1073127 ]
 [-1.52243774  1.57252997 -0.12039762]]
Матрица В:
[[ 0.99868312  0.89376939 -0.61074471 -1.12385734  0.66040089 -0.91913062
  -0.02449929  1.36365428]
 [ 0.97478315 -0.01397683 -0.35772058  0.51972094 -0.41855506 -1.63309415
  -0.10774528 -0.1550127 ]
 [ 0.68514808  0.89304414  1.35048173  0.84497257  0.66706621 -0.33191552
   1.20261482  0.26778718]]
Результат умножения А * В:
[[ 1.30536376  1.21802006  2.27902833  2.00290549  0.7190238  -1.04901031
   1.97135792 -0.03900083]
 [-1.20359936 -0.37280511 -0.39548456 -1.01621504  0.1110891   1.6587184
  -0.51307785  0.11806993]
 [-1.28166459  0.04717142 -1.24837458 -2.7081064   0.69773501  2.10966828
  -0.96204187  1.30660151]
 [ 3.6422041   3.36365257  3.570

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .
Обе матрицы  𝐴*𝐵  и  𝐵*𝐴  определены и имеют размерность  4×4

In [5]:
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Результат умножения А * В:')
print(A.dot(B))
print('Результат умножения В * А:')
print(B.dot(A))

Матрица А:
[[-1.25948722  0.32719748  0.02590834 -1.66858714]
 [-0.84261854  0.77373103  1.76568095 -2.41172347]
 [ 0.53900335  1.36822213 -1.17537325 -1.06516269]
 [-0.92720098  0.62209096  1.25370548  0.29097442]]
Матрица В:
[[ 0.7653987  -1.28749457  0.80720811 -2.96613846]
 [-0.52314561 -0.05461213 -0.34194279 -0.66348273]
 [-0.03710414  0.93548888 -0.85531351  0.02059588]
 [ 1.89109947 -0.69027449  0.28875504  0.49938422]]
Результат умножения А * В:
[[-4.29160737  2.7797341  -1.63252382  2.68599113]
 [-5.67603617  4.35913777 -3.15134835  0.8179552 ]
 [-2.27394432 -1.13297939  0.6649757  -3.0626836 ]
 [-0.53137868  2.13176783 -1.94945457  2.50858908]]
Результат умножения В * А:
[[ 3.30615128 -1.48650591 -6.92090927  0.10506807]
 [ 1.13578593 -1.09402733 -0.53988295  1.17579161]
 [-1.22164145 -0.44576996  2.68194737 -1.27718809]
 [-2.10756713  0.79041963 -0.88312349 -1.65297614]]


2. Найти сумму и произведение матриц  𝐴=([[1, -2], [3, 0]])  и  𝐵=([[4, -1], [0, 5]]).

In [6]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Сумма матриц:')
print(A + B)
print('Результат умножения А * В:')
print(A.dot(B))

Матрица А:
[[ 1 -2]
 [ 3  0]]
Матрица В:
[[ 4 -1]
 [ 0  5]]
Сумма матриц:
[[ 5 -3]
 [ 3  5]]
Результат умножения А * В:
[[  4 -11]
 [ 12  -3]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. 
Вычислить линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц  
𝐴=([[1, 7], [3, -6]]) ,  
𝐵=([[0,5], [2, -1]]) ,  
𝐶=([[2, -4], [1, 1]]).

#### 3𝐴−2𝐵+4𝐶 = [[3*1 - 0 + 4*2, 3*7 -2*5 - 4* 4],[3*3 - 2*2 +4, -6*3 +1*2 +4*1]] =
#### = [[11, -5],[9, 12]]

In [7]:
#Проверка
A = np.array([[1, 7], [3, -6]])
B = np.array([[0,5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print('Матрица А:')
print(A)
print('Матрица В:')
print(B)
print('Матрица С:')
print(C)
print('Результат 3𝐴−2𝐵+4𝐶 :')
print(3*A - 2*B + 4*C)

Матрица А:
[[ 1  7]
 [ 3 -6]]
Матрица В:
[[ 0  5]
 [ 2 -1]]
Матрица С:
[[ 2 -4]
 [ 1  1]]
Результат 3𝐴−2𝐵+4𝐶 :
[[ 11  -5]
 [  9 -12]]


4. Дана матрица  𝐴=[[4, 1], [5, -2], [2, 3]] . Вычислить  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print('Матрица А:')
print(A)
print('Результат умножения А * А.Т:')
print(np.dot(A, A.T))
print('Результат умножения А.Т * А:')
print(np.dot(A.T, A))

Матрица А:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Результат умножения А * А.Т:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Результат умножения А.Т * А:
[[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

1. Вычислить определитель:

a)||𝑠𝑖𝑛𝑥 −𝑐𝑜𝑠𝑥||; 
   ||𝑐𝑜𝑠𝑥 𝑠𝑖𝑛𝑥||;

detA = sinxsinx + cosxcosx = 1

In [9]:
x = np.pi
A = np.array([[np.sin(x), -np.cos(x)],[np.cos(x), np.sin(x)]])
A
np.linalg.det(A)

1.0

б)||4 2 3 ||
  ||0 5 1 ||
  ||0 0 9||;
B - верхняя треугольная матрица
det(B) = 4 * 5 * 9 = 180

In [10]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0 ,9]])
np.linalg.det(B)

180.0

в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Матрица линейно зависимая:
    Второй столбец - Первый столбец = Третий столбец - Второй столбец. 
    Определитель = 0

In [11]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{np.linalg.det(C):.1f}')

-0.0


2. Определитель матрицы  𝐴  равен  4 . Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2})$ = 4**2 = 16

б) $det(A^{T})$ = 4

в) $det(2A)$ = 2 * 4 = 8

3. Доказать, что матрица
$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
 
вырожденная.

In [ ]:
# 1 и 2 строки матриц линейно зависимы, определитель равен 0.
# Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'{np.linalg.det(A):.1f}')

4. Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [12]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


  б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [13]:

b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
