In [12]:
import pprint
import numpy as np
import scipy
import scipy.linalg

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

In [ ]:
Случай, когда 3 измерения, вектора 4.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} \Rightarrow \begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

Получившаяся система имеет бесконечное число решений. 

Найдём общее решение системы, при $x_4=c$:
$$-2x_3+3c=4 \; \Leftrightarrow \; x_3=\frac{3c-4}{2}=1.5c-2$$
$$-x_2+\frac{3c-4}{2}+5c=-2 \; \Leftrightarrow \; x_2=\frac{13c}{2}=7.5c$$
$$x_1+\frac{13c}{2}-\frac{3c-4}{2}-2c=0 \; \Leftrightarrow \; x_1=\frac{-6c-4}{2}=-3c-2$$

Частное решение системы, при $c=0$:
$$x_1=-2$$
$$x_2=0$$
$$x_3=-2$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Преобразования: 

Переместили 3е уравнение на 1 строку. 

Из 2го уравнения вычли 2 1*х. 

Из 1го уравения вычли  3 1*х и 4 2*х. 

2 и 3 столбец поменяли местами

$\begin{pmatrix}\left.\begin{matrix}
3 & -1 & 1\\
2 & -5 & -3\\
1 & 1 & -1
\end{matrix}\right|\begin{matrix} 
4\\
-17\\
0
\end{matrix}\end{pmatrix} = \begin{pmatrix}\left.\begin{matrix}
1 & -1 & 1\\
0 & -1 & -7\\
0 & 0 & -32
\end{matrix}\right|\begin{matrix} 
0\\
-17\\
-64
\end{matrix}\end{pmatrix}$

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

$\begin{pmatrix}\left.\begin{matrix}
2 & -4 & 6\\
1 & -2 & 3\\
3 & -6 & 9
\end{matrix}\right|\begin{matrix} 
1\\
-2\\
5
\end{matrix}\end{pmatrix} = \begin{pmatrix}\left.\begin{matrix}
0 & 0 & 0\\
1 & -2 & 3\\
0 & 0 & 0
\end{matrix}\right|\begin{matrix} 
5\\
-2\\
11
\end{matrix}\end{pmatrix} $

Система несовместна и не имеет решений

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$\begin{pmatrix}\left.\begin{matrix}
1 & 2 & 5\\
3 & 1 & -8
\end{matrix}\right|\begin{matrix} 
4\\
-2
\end{matrix}\end{pmatrix} = \begin{pmatrix}\left.\begin{matrix}
1 & 2 & 5\\
0 & -5 & -23
\end{matrix}\right|\begin{matrix} 
4\\
-14
\end{matrix}\end{pmatrix} $

Система совместна и имеет бесконечное множество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Решение: 

x4 = 0.5

x3 = 4/3

x2 = (2- 0.5)/5 = 0.3

x1 = 3 -2 + 8/3 - 3*0.3 = 73/30

Ответ: система совместна и имеет 1 решение (73/30, 3/10, 4/3, 1/2)

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\tilde{A}=\begin{pmatrix}\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|\begin{matrix}
a\\ 
b\\
c
\end{matrix}\end{pmatrix} = \tilde{A}=\begin{pmatrix}\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|\begin{matrix}
a\\ 
b-4a\\
8a-2b+c-7
\end{matrix}\end{pmatrix}$$




$$8a-2b+c-7 \neq 0$$

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$$det A = \begin{vmatrix}
1 & -2\\
3 & -4
\end{vmatrix} = -4 + 6 = 2$$

$$det A_1 = \begin{vmatrix}
1 & -2\\
7 & -4
\end{vmatrix} = -4 + 14 = 10$$

$$det A_2 = \begin{vmatrix}
1 & 1\\
3 & 7
\end{vmatrix} = 7 - 3 = 4$$

$$x_1=\frac{det A_1}{det A}=5$$

$$x_2=\frac{det A_2}{det A}=2$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


$$det A = \begin{vmatrix}
2 & -1 & 5\\
1 & 1 & -3\\
2 & 4 & 1
\end{vmatrix} = 2 + 6 + 20 + 24 + 1 - 10 = 43$$

$$det A_1 = \begin{vmatrix}
10 & -1 & 5\\
-2 & 1 & -3\\
1 & 4 & 1
\end{vmatrix} = 10 + 3 - 40 - 5 - 2 + 120 = 86$$

$$det A_2 = \begin{vmatrix}
2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1
\end{vmatrix} = -4 -60 +5 +20 -10 +6 = -43$$

$$det A_3 = \begin{vmatrix}
2 & -1 & 10\\
1 & 1 & -2\\
2 & 4 & 1
\end{vmatrix} = 2 + 4 + 40 - 20 + 1 + 16 = 43$$

$$x_1=\frac{det A_1}{det A}=2$$

$$x_2=\frac{det A_2}{det A}=-1$$

$$x_3=\frac{det A_3}{det A}=1$$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [13]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])
P (permutation):
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])
U:
array([[ 3.        , 26.        , 30.        ],
       [ 0.        , -8.33333333, -8.        ],
       [ 0.        ,  0.        ,  0.4       ]])


   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [14]:
B = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(B)
print("B:")
pprint.pprint(B)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

B:
array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])
P:
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])
U:
array([[  4.        ,  22.        ,  53.        ,  33.        ],
       [  0.        ,  -6.        , -18.5       ,  -7.5       ],
       [  0.        ,   0.        , -15.375     ,  -8.625     ],
       [  0.        ,   0.        ,   0.        ,  -0.09756098]])


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$


In [15]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])
P (permutation):
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])
U:
array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])


In [16]:
#По верхней матрице
y1 = 1
y2 = -6 - 0.82
y3 = -5 -0.18 +0.12*y2
print(f'y1: {y1:.1f}, y2: {y2:.1f}, y3: {y3:.1f}')

y1: 1.0, y2: -6.8, y3: -6.0


In [17]:
#По нижней матрице
x3 = y3/2.08
x2 = (y2 + 0.09 * x3)/ 2.27
x1 = (y1- 5*x3 - 7*x2)/11
print(f'x1: {x1:.1f}, x2: {x2:.1f}, x3: {x3:.1f}')

x1: 3.4, x2: -3.1, x3: -2.9
