In [1]:
from numpy.linalg import norm
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist

### Lesson 2

1. Найти скалярное произведение векторов 𝑥,𝑦∈ℝ:

а) 𝑥=(0,−3,6), 𝑦=(−4,7,9);

б)  𝑥=(7,−4,0,1), 𝑦=(−3,1,11,2).

a) (x,y) = (0, -3, 6) * (-4, 7, 9) = (0 + (-3)*7 + 6*9) = -21 + 54 =33

In [3]:
#Check
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
np.dot(x, y)

33

b) (x,y) = (7, -4, 0, 1) *(-3, 1, 11, 2) = (7 *(-3) - 4 + 0 + 2) = -21 -2 = -23

In [4]:
#Check
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
np.dot(x, y)

-23

2. Найти нормы векторов  (4,2,4)  и  (12,3,4)  и угол между ними.

Определим манхэттенскую норму:
a = (4, 2, 4)
||a||1 = 4 + 2 + 4 = 10

b = (12, 3, 4)
||b||1 = 12 + 3 + 4 = 19

In [5]:
#check
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])
print(norm(a, ord=1))
print(norm(b, ord=1))

10.0
19.0


Определим евклидову норму:

||a||2 = (4*4 + 2*2 + 4*4) ** 0.5 = 6

||b||2 = (12 ** 2 + 3*3 + 4*4) ** 0.5 = 13

In [11]:
#check
print(norm(a, ord=2))
print(norm(b, ord=2))

6.0
13.0


In [9]:
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.2f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.2f}')

Косинус угла между a и b: 0.90
Угол между a и b: 0.46


3. Будет ли линейное пространство евклидовым, если за скалярное произведение принять:
а) произведение длин векторов;
б) утроенное обычное скалярное произведение векторов?

Определение. Линейное пространство E называется евклидовым,если в нем определено скалярное произведение.
Значит: а) можно, б) можно

4. Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве  ℝ3 :

а)  (1,0,0),(0,0,1);  

б)  (1/2⎯⎯√,−1/2⎯⎯√,0),(1/2⎯⎯√,1/2⎯⎯√,0),(0,0,1); 

в)  (1/2,−1/2,0),(0,1/2,1/2),(0,0,1); 

г)  (1,0,0),(0,1,0),(0,0,1)?

In [14]:
# а)  (1,0,0),(0,0,1);
a = np.array([1, 0, 0])
b = np.array([0, 0, 1])
print(np.dot(a, b))

#Ортонормированный базис

0


In [20]:
#б)  (1/2⎯⎯√,−1/2⎯⎯√,0),(1/2⎯⎯√,1/2⎯⎯√,0),(0,0,1); 
c = np.array([(1/(2**0.5)), (-1/(2**0.5)), 0])
d = np.array([(1/(2**0.5)), (1/(2**0.5)), 0])
b = np.array([0, 0, 1])
print(np.dot(c, d))
print(np.dot(c, b))
print(np.dot(b, d))
print(f'{norm(c):.1f}, {norm(d):.1f}, {norm(b):.1f}')

#Ортонормированный базис

0.0
0.0
0.0
1.0, 1.0, 1.0


In [19]:
#в)  (1/2,−1/2,0),(0,1/2,1/2),(0,0,1); 
e = np.array([0.5, -0.5, 0])
f = np.array([0, 0.5, 0.5])
b = np.array([0, 0, 1])

print(np.dot(e, f))
print(np.dot(e, b))
print(np.dot(b, f))
print(norm(e), norm(f), norm(b))

#Не ортогональный, не ортонормированный базис

-0.25
0.0
0.5
0.7071067811865476 0.7071067811865476 1.0


In [ ]:
#г)  (1,0,0),(0,1,0),(0,0,1)

#Ортонормированный базис

### Lesson 3

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

Матрицы А и В не квадратные, одинаковой размерности. Соответственно умножать их можно, если 1 из них транспонировать.
Если транспонировать 2ой множитель, получится матрица 4*4
Если транспонировать 1ый множитель, то получится матрица 2*2

In [28]:
A = np.random.randn(4, 2)
B = np.random.randn(4, 2)
print(A)
print(B)
print(A.dot(B.T))
print(B.T.dot(A))

[[-0.17856957 -0.72772601]
 [ 0.75884085  0.2411668 ]
 [-1.28029538 -1.28090746]
 [-0.06965324  1.64491769]]
[[ 0.04167591  0.23585022]
 [ 0.3523656  -0.34720887]
 [-0.05512024 -0.35807071]
 [ 0.63115103 -0.71532954]]
[[-0.17907639  0.18975115  0.27042017  0.40785954]
 [ 0.08850463  0.18365416 -0.12818226  0.30642945]
 [-0.35545979 -0.00638962  0.52922563  0.1082112 ]
 [ 0.38505134 -0.59567341 -0.58515755 -1.22061994]]
[[ 0.28655583  1.16344565]
 [ 0.20266935 -0.97337237]]


б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;
Матрицы 𝐴𝐵 имеет размерность 2 * 3
Матрица ВА не существует. Можно сделать матрицу A.T * B.T. Размерность 3 * 2

In [32]:
A = np.random.randn(2, 5)
B = np.random.randn(5, 3)
print(A)
print(B)
print(A.dot(B))
print(B.T.dot(A.T))

[[ 0.49043024 -0.45438987 -0.77376185 -0.04883134  0.21909953]
 [ 0.33875672  1.61335902 -0.12041033 -1.84833239  1.42063036]]
[[ 0.89653346 -0.47253801  0.06604449]
 [ 0.24897095 -0.53555653 -0.14279172]
 [-1.15887638  1.13530256  0.21923955]
 [ 1.98638704 -1.9672779  -0.4931269 ]
 [-0.25198607 -0.52111581 -0.39352155]]
[[ 1.0710436  -0.88496069 -0.13450622]
 [-3.18455563  1.73504799  0.11801376]]
[[ 1.0710436  -3.18455563]
 [-0.88496069  1.73504799]
 [-0.13450622  0.11801376]]


в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

Обе матрицы  𝐴𝐵  и  𝐵𝐴  определены
Матрицы 𝐴𝐵 имеет размерность 8 * 8
Матрица ВА имеет размерность 3 * 3

In [35]:
A = np.random.randn(8, 3)
B = np.random.randn(3, 8)
print(A)
print(B)
print(A.dot(B))
print(B.dot(A))

[[ 0.05932566 -0.30749369  1.47758207]
 [-0.98910208 -0.0093617  -1.24852873]
 [-1.14520337  1.145154   -1.39502533]
 [-0.15984359  0.13430962  0.23548241]
 [ 2.25068889  0.20132877 -0.57012777]
 [ 1.14951976  0.55331743  0.41064855]
 [ 0.02772506 -0.44508832  0.96447873]
 [-0.52034178  0.02050596 -0.15759613]]
[[-0.07048985 -0.3020862   0.33128027  0.64851821  0.19442502 -0.28678877
  -0.148885    0.92248926]
 [-0.70738884 -0.82952026 -0.40995405 -0.10917284  1.14957633  0.73521686
  -2.1167215  -0.6597924 ]
 [ 0.09666343  0.83601688  2.17093839 -0.09270609  0.66311161  1.4092562
  -1.6533359  -1.68201006]]
[[ 0.3561639   1.47243433  3.35345134 -0.06493713  0.63784875  1.83920321
  -1.80089367 -2.22769862]
 [-0.04434304 -0.73723128 -3.03431109 -0.52468245 -1.03098208 -1.48271636
   2.23131594  1.19377861]
 [-0.86419187 -1.77024302 -3.87735784 -0.73837761  0.16872825 -0.7955801
   0.05297697  0.53444492]
 [-0.06097924  0.13374126  0.40320401 -0.1401551   0.27947269  0.4764431
  -0.6498

In [ ]:
г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .
Обе матрицы  𝐴𝐵  и  𝐵𝐴  определены и имеют размерность  4×4

In [36]:
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)
print(A)
print(B)
print(A.dot(B))
print(B.dot(A))

[[ 0.53623299  2.70103549 -0.30703383  1.95159997]
 [ 1.83559184 -0.41679241 -1.40052141  1.46212094]
 [ 0.43424863 -0.20422353 -1.01093544 -0.394122  ]
 [ 0.25488046  0.25799521  0.51072021 -0.20955152]]
[[ 0.68977183 -0.38933021 -0.01460199  0.36907782]
 [ 2.0074626   0.13987372 -0.8951195   1.14621455]
 [-0.73965952  0.22278403 -0.62935372 -1.03072127]
 [-0.38731461 -0.96058384  0.76398026 -1.39030344]]
[[ 5.26332345 -1.77404546 -0.74136287  0.89702804]
 [ 0.89905257 -2.48945321  2.34473061 -0.38950186]
 [ 0.7899586  -0.04426467  0.51159813  1.51612939]
 [ 0.3971284   0.2519262  -0.7161752   0.1547186 ]]
[[-0.25704311  2.12357045  0.53673918  0.70532498]
 [ 1.23666201  5.84245175  0.6780479   4.23487152]
 [-0.52369599 -2.22809363  0.02491249 -0.65375095]
 [-1.99353453 -1.16050083 -0.01815388 -2.17013415]]


2. Найти сумму и произведение матриц  𝐴=(1 3−2 0)  и  𝐵=(4 0−1 5).

In [3]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(A)
print(B)
print(A + B)
print(np.dot(A, B))

[[ 1 -2]
 [ 3  0]]
[[ 4 -1]
 [ 0  5]]
[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц  𝐴=(137−6) ,  𝐵=(025−1) ,  𝐶=(21−41).

3𝐴−2𝐵+4𝐶 = (3 - 0 + 4 * 2      3*7 - 2*5 -4*4)  = ([11,-5],
            (3*3 -2*2 + 4      -6*3+2 + 4)         [9, -12])

In [4]:
#Check
A = np.array([[1, 7], [3, -6]])
B = np.array([[0,5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(A)
print(B)
print(C)
print(3*A - 2*B + 4*C)

[[ 1  7]
 [ 3 -6]]
[[ 0  5]
 [ 2 -1]]
[[ 2 -4]
 [ 1  1]]
[[ 11  -5]
 [  9 -12]]


4. Дана матрица  𝐴=4521−23 . Вычислить  𝐴𝐴𝑇  и  𝐴𝑇𝐴 .

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(A)
print(np.dot(A, A.T))
print(np.dot(A.T, A))

[[ 4  1]
 [ 5 -2]
 [ 2  3]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


### Lesson 4

1. Вычислить определитель:

a) ||𝑠𝑖𝑛𝑥 −𝑐𝑜𝑠𝑥||;
    ||𝑐𝑜𝑠𝑥   𝑠𝑖𝑛𝑥||

𝑑𝑒𝑡𝐴=|𝐴|=||||𝑎11𝑎21𝑎12𝑎22||||=𝑎11𝑎22−𝑎12𝑎21.
detA = sinx*sinx + cosx*cosx = 1

In [10]:
x = np.pi
A = np.array([[np.sin(x), -np.cos(x)],[np.cos(x), np.sin(x)]])
A
np.linalg.det(A)

1.0

б)||4 2 3 ||
  ||0 5 1 ||
  ||0 0 9||;
  
det(B) = 4*5*9 = 180

In [11]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0 ,9]])
np.linalg.det(B)

180.0

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

|1 2 3|     |1 2 3|    |1 2 3|
|4 5 6| <=> |2 1 0| <=>|2 1 0| <=> det(C) = 0
|7 8 9|     |4 2 0|    |0 0 0|

In [14]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{np.linalg.det(C):.1f}')

0.0



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$ = 4**2 = 16;

   б) $det(A^{T})$ = 4

   в) $det(2A)$ = 2 * 4 = 8 .

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [16]:
# 1 и 2 строки матриц линейно зависимы, определитель равен 0.
# Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'{np.linalg.det(A):.1f}')

0.0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [17]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [18]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
