__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

  б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [2]:
import numpy as np
A = np.array([[1, -2], [3, -4]])
B = np.array([[1, -2], [7, -4]])
C = np.array([[1, 1], [3, 7]])
print(A)
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(C))

[[ 1 -2]
 [ 3 -4]]
2.0000000000000004
9.999999999999998
3.999999999999999


In [4]:
#Решения по формулам Крамера:
x1= np.linalg.det(B)/np.linalg.det(A)
x2 = np.linalg.det(C)/np.linalg.det(A)
print(f'x1: {x1:.1f}, x2: {x2:.1f}')

x1: 5.0, x2: 2.0


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [5]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
B = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
C = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
D = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])

#Решения по формулам Крамера:
x1= np.linalg.det(B)/np.linalg.det(A)
x2 = np.linalg.det(C)/np.linalg.det(A)
x3 = np.linalg.det(D)/np.linalg.det(A)
print(f'x1: {x1:.1f}, x2: {x2:.1f}, x3: {x3:.1f}')

x1: 2.0, x2: -1.0, x3: 1.0


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [7]:
import pprint
import scipy
import scipy.linalg

A = scipy.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])
P (permutation):
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])
U:
array([[ 3.        , 26.        , 30.        ],
       [ 0.        , -8.33333333, -8.        ],
       [ 0.        ,  0.        ,  0.4       ]])


   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [8]:
B = scipy.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(B)
print("B:")
pprint.pprint(B)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

B:
array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])
P:
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])
U:
array([[  4.        ,  22.        ,  53.        ,  33.        ],
       [  0.        ,  -6.        , -18.5       ,  -7.5       ],
       [  0.        ,   0.        , -15.375     ,  -8.625     ],
       [  0.        ,   0.        ,   0.        ,  -0.09756098]])


__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [18]:
A = scipy.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])
P (permutation):
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])
U:
array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])


In [13]:
#По верхней матрице
y1 = 1
y2 = -6 - 0.82
y3 = -5 -0.18 +0.12*y2
print(f'y1: {y1:.1f}, y2: {y2:.1f}, y3: {y3:.1f}')

y1: 1.0, y2: -6.8, y3: -6.0


In [21]:
#По нижней матрице
x3 = y3/2.08
x2 = (y2 + 0.09 * x3)/ 2.27
x1 = (y1- 5*x3 - 7*x2)/11
print(f'x1: {x1:.1f}, x2: {x2:.1f}, x3: {x3:.1f}')

x1: 3.4, x2: -3.1, x3: -2.9
